_wandb:
    value:
        cli_version: 0.25.1
        e:
            wani8msxe3fh4e0nz75zvbofyiuwfnn4:
                codePath: train.py
                codePathLocal: train.py
                cpu_count: 30
                cpu_count_logical: 30
                cudaVersion: "13.2"
                disk:
                    /:
                        total: "1054682689536"
                        used: "956421529600"
                email: s31890@pjwstk.edu.pl
                executable: /home/boro_arch_usr/Documents/Code/MiniPetDetectorCOV/.venv/bin/python3
                git:
                    commit: 4569a3fafe7cc3d2cd71f3bf01e85cf7d8724279
                    remote: git@github.com:johnyboro/MiniPetDetectorCOV.git
                gpu: NVIDIA GeForce GTX 1650
                gpu_count: 1
                gpu_nvidia:
                    - architecture: Turing
                      cudaCores: 896
                      memoryTotal: "4294967296"
                      name: NVIDIA GeForce GTX 1650
                      uuid: GPU-b923fdf2-4301-4267-8377-d4571c9da0b5
                host: boroarchkvm
                memory:
                    total: "16734941184"
                os: Linux-6.19.10-arch1-1-x86_64-with-glibc2.43
                program: /home/boro_arch_usr/Documents/Code/MiniPetDetectorCOV/train.py
                python: CPython 3.12.11
                root: /home/boro_arch_usr/Documents/Code/MiniPetDetectorCOV
                startedAt: "2026-04-12T15:57:49.295359Z"
                writerId: wani8msxe3fh4e0nz75zvbofyiuwfnn4
        m: []
        python_version: 3.12.11
        t:
            "1":
                - 1
                - 5
                - 41
                - 53
            "2":
                - 1
                - 5
                - 41
                - 53
            "3":
                - 1
                - 2
                - 13
                - 16
            "4": 3.12.11
            "5": 0.25.1
            "12": 0.25.1
            "13": linux-x86_64
architecture:
    value: LeNet5Like
device:
    value: cuda
epochs:
    value: 10
lr:
    value: 0.001
num_classes:
    value: 37
optimizer:
    value: Adam
