_wandb:
    value:
        cli_version: 0.25.1
        e:
            oy3fyyydl3kah66lvx7nabsmopkodc3v:
                codePath: train.py
                codePathLocal: train.py
                cpu_count: 30
                cpu_count_logical: 30
                cudaVersion: "13.2"
                disk:
                    /:
                        total: "1054682689536"
                        used: "956863205376"
                email: s31890@pjwstk.edu.pl
                executable: /home/boro_arch_usr/Documents/Code/MiniPetDetectorCOV/.venv/bin/python3
                git:
                    commit: fd450823f7135fc4fa04f9edbce263105f9513cf
                    remote: git@github.com:johnyboro/MiniPetDetectorCOV.git
                gpu: NVIDIA GeForce GTX 1650
                gpu_count: 1
                gpu_nvidia:
                    - architecture: Turing
                      cudaCores: 896
                      memoryTotal: "4294967296"
                      name: NVIDIA GeForce GTX 1650
                      uuid: GPU-b923fdf2-4301-4267-8377-d4571c9da0b5
                host: boroarchkvm
                memory:
                    total: "16734928896"
                os: Linux-6.19.11-arch1-1-x86_64-with-glibc2.43
                program: /home/boro_arch_usr/Documents/Code/MiniPetDetectorCOV/train.py
                python: CPython 3.12.11
                root: /home/boro_arch_usr/Documents/Code/MiniPetDetectorCOV
                startedAt: "2026-04-13T15:54:16.343528Z"
                writerId: oy3fyyydl3kah66lvx7nabsmopkodc3v
        m: []
        python_version: 3.12.11
        t:
            "1":
                - 1
                - 5
                - 41
                - 53
            "2":
                - 1
                - 5
                - 41
                - 53
            "3":
                - 1
                - 2
                - 13
                - 16
            "4": 3.12.11
            "5": 0.25.1
            "12": 0.25.1
            "13": linux-x86_64
data.batch_size:
    value: 32
data.img_size:
    value:
        - 224
        - 224
data.num_workers:
    value: 8
data.test_ratio:
    value: 0.1
data.val_ratio:
    value: 0.1
model.name:
    value: lenet5_like
model.num_classes:
    value: 37
optimizer.lr:
    value: 0.001
optimizer.name:
    value: adam
optimizer.weight_decay:
    value: 0
train.device:
    value: auto
train.epochs:
    value: 10
wandb.entity:
    value: johnyboro-personal
wandb.mode:
    value: online
wandb.project:
    value: MiniPetDetector
wandb.run_name:
    value: lenet5-like-baseline
wandb.watch_model:
    value: true
