wandb:
  entity: johnyboro-personal
  project: MiniPetDetector
  run_name: lenet5-like-baseline
  mode: online

model:
  name: lenet5_like
  num_classes: 37

train:
  epochs: 10
  device: auto

optimizer:
  name: adam
  lr: 0.001
  weight_decay: 0.0
